CSect   Symbol  Value   LENGTH  Flags:
--------------------------------------
SUM             000000  2F07  
        FIRST   000000          R
        LOOP    00000A          R
        MYLIT   00001D          R
        COUNT   000021          R
        TABLE   000024          R
        TABLE2  001794          R
        TOTAL   002F04          R

Literal Table
Name  Operand   Address  Length:
--------------------------------
