CSect   Symbol  Value   LENGTH  Flags:
--------------------------------------
COPY            000000  1076  
        FIRST   000000          R
        CLOOP   000006          R
        ENDFIL  00001A          R
        RETADR  000030          R
        LENGTH  000033          R
        BUFFER  000036          R
        BUFEND  001036          R
        MAXLEN  001036          R
        RDREC   001036          R
        RLOOP   001040          R
        EXIT    001056          R
        INPUT   00105C          R
        WRREC   00105D          R
        WLOOP   001062          R

Literal Table
Name  Operand   Address  Length:
--------------------------------
EOF   454F46    002D     3
05    05        1076     2
